server:
  port: 8089
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/pdf
    min-response-size: 1024

spring:
  application:
    name: print-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
  packages-to-scan: br.com.brazilsistem.print_service.resource
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    root: INFO
    br.com.brazilsistem.print_service: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
